name: Update API specs
on:
  workflow_dispatch:
  schedule:
  - cron: '0 1 10-31 * THU,FRI'

jobs:
  update-api-specs:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Check out repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Set up Anbox Cloud
      uses: canonical/anbox-cloud-github-action@ded37ace13709f90281baa9db7379c76ecef7cf1
      with:
        channel: latest/stable
    - name: Determine appliance version
      id: snap_version
      run: |
        echo "value=$(snap info anbox-cloud-appliance | awk '/installed/{print $2}')" >> "$GITHUB_OUTPUT"
    - name: Extract API spec from AMS
      run: |
        sudo apt update
        sudo apt install -y jq yq
        # Don't allow us to succeed if the actual curl command fails
        set -o pipefail
        curl \
          --unix-socket /var/snap/anbox-cloud-appliance/common/ams-unix.socket \
          s/1.0/swagger.json | yq -y > ./reference/api-reference/ams-api.yaml
        sudo curl \
          --unix-socket /var/snap/anbox-cloud-appliance/common/gateway/internal.sock \
          s/1.0/swagger.json | yq -y > ./reference/api-reference/gateway-api.yaml
    - name: Create pull request
      uses: canonical/create-pull-request@214a47c7e33f3066cc650834a052377912cdccf2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "feat: update API specs from ${{ steps.snap_version.outputs.value }}"
        branch-name: update-api-specs-${{ steps.snap_version.outputs.value }}
        title: Update API specs from ${{ steps.snap_version.outputs.value }}
        body: |
          This updates the AMS API specification as taken from the `anbox-cloud-appliance` as of
          version ${{ steps.snap_version.outputs.value }}.

          You have to close and reopen the PR to trigger checks.
        repository: canonical/anbox-cloud-docs
        upsert: true
        ignore-no-changes: true
